<?php
declare(strict_types=1);

/** Groups the site texts under Bengali headings so each one is easy to find in the admin. */
return [
    'হেডার ও ফুটার' => [
        'appName' => 'অ্যাপের নাম (হেডার ও ফুটারে)',
        'appTagline' => 'উপশিরোনাম / ট্যাগলাইন (হেডার ও ফুটারে)',
        'lastUpdated' => '"সর্বশেষ আপডেট" লেখা (হেডারে)',
        'footerNote1' => 'ফুটার — প্রথম নোট',
        'footerNote2' => 'ফুটার — দ্বিতীয় নোট',
        'mainMenuAria' => 'মূল মেনুর বর্ণনা (স্ক্রিন রিডারের জন্য)',
        'pageTitle' => 'ব্রাউজার ট্যাবের টাইটেল',
        'backHome' => '"হোমে ফিরে যান" বাটন',
    ],
    'মেনুর ট্যাব' => [
        'tabOverview' => '১ম ট্যাব — একনজরে ক্যালেন্ডার',
        'tabInfo' => '২য় ট্যাব — তথ্যকণিকা',
        'tabEligibility' => '৩য় ট্যাব — আবেদনযোগ্যতা যাচাই',
    ],
    'হোম পেজ — পরিসংখ্যান ও সামনের পরীক্ষা' => [
        'statTotal' => 'পরিসংখ্যান: মোট প্রতিষ্ঠান',
        'statUpcoming' => 'পরিসংখ্যান: আসন্ন ভর্তি পরীক্ষা',
        'statThisWeek' => 'পরিসংখ্যান: এই সপ্তাহে পরীক্ষা',
        'sectionUpcoming' => 'শিরোনাম: সামনে যেসব ভর্তি পরীক্ষা',
        'emptyUpcomingTitle' => 'খালি থাকলে শিরোনাম',
        'emptyUpcomingDesc' => 'খালি থাকলে বিবরণ',
        'urgentLabel' => 'ডেডলাইন ব্যানারের লেবেল',
        'noticeLabel' => 'জরুরি নোটিশ ব্যানারের লেবেল',
        'todayLastDay' => 'ডেডলাইন: আজ শেষ দিন',
        'daysLeftTemplate' => 'ডেডলাইন: "আর মাত্র {n} দিন বাকি"',
        'deadlinePrefix' => 'ডেডলাইন বার্তার শুরুর শব্দ (যেমন "আবেদনের")',
    ],
    'হোম পেজ — সময়সূচি টেবিল' => [
        'sectionSchedule' => 'শিরোনাম: সকল বিশ্ববিদ্যালয়ের ভর্তি সময়সূচি',
        'searchPlaceholder' => 'খোঁজার বক্সের ভেতরের লেখা',
        'searchAria' => 'খোঁজার বক্সের বর্ণনা (স্ক্রিন রিডার)',
        'categoryFilterAria' => 'ক্যাটাগরি ফিল্টারের বর্ণনা',
        'allCategories' => 'ফিল্টার: সব ক্যাটাগরি',
        'statusFilterAria' => 'অবস্থা ফিল্টারের বর্ণনা',
        'statusAll' => 'ফিল্টার: সব অবস্থা',
        'statusOngoing' => 'ফিল্টার ও অবস্থা: আবেদন চলছে',
        'applicationEnd' => 'ফিল্টার ও কলাম: আবেদন শেষ',
        'statusUpcomingExam' => 'ফিল্টার: পরীক্ষা আসন্ন',
        'statusCompleted' => 'ফিল্টার: পরীক্ষা সম্পন্ন',
        'colNo' => 'কলাম: ক্রম',
        'colCategory' => 'কলাম: ক্যাটাগরি',
        'colUniversity' => 'কলাম: বিশ্ববিদ্যালয়',
        'colUnit' => 'কলাম: ইউনিট',
        'applicationStart' => 'কলাম: আবেদন শুরু',
        'examDate' => 'কলাম: ভর্তি পরীক্ষা',
        'colDaysLeft' => 'কলাম: বাকি দিন',
        'details' => 'বাটন: বিস্তারিত',
        'emptyResults' => 'ফলাফল না থাকলে শিরোনাম',
        'emptyResultsDesc' => 'ফলাফল না থাকলে বিবরণ',
        'notPublished' => 'তারিখ না থাকলে লেখা (বিস্তারিত)',
        'notPublishedShort' => 'তারিখ না থাকলে লেখা (সংক্ষিপ্ত)',
    ],
    'ক্যাটাগরি পেজ' => [
        'categoryPickTitle' => 'শিরোনাম: ক্যাটাগরি বেছে নিন',
        'categoryPickDesc' => 'শিরোনামের নিচের বিবরণ',
        'institutionCountSuffix' => 'প্রতিষ্ঠান সংখ্যার পরের লেখা (যেমন "টি প্রতিষ্ঠান")',
        'backToCategoryAria' => 'ক্যাটাগরি তালিকায় ফেরার বাটনের বর্ণনা',
        'emptyCategory' => 'ক্যাটাগরিতে তথ্য না থাকলে বার্তা',
    ],
    'তথ্যকণিকা' => [
        'sectionImportantDates' => 'সেকশন: গুরুত্বপূর্ণ তারিখ',
        'admissionSession' => 'ভর্তি সেশনের লেবেল',
        'sectionSeats' => 'সেকশন: আসন সংখ্যা',
        'totalSeats' => 'আসন সংখ্যার লেবেল: মোট আসন',
        'sectionEligibility' => 'সেকশন: আবেদন যোগ্যতা',
        'sectionExamPattern' => 'সেকশন: পরীক্ষার ধরন',
        'sectionSubjects' => 'সেকশন: বিষয় ও প্রশ্নসংখ্যা',
        'sectionResultMethod' => 'সেকশন: ফলাফল নির্ণয় পদ্ধতি',
        'sectionCircular' => 'সেকশন: অফিসিয়াল সার্কুলার',
        'circularNotPublished' => 'সার্কুলার না থাকলে লেখা',
        'viewCircular' => 'বাটন: অফিশিয়াল সার্কুলার দেখুন',
        'viewDetails' => 'বাটন: বিস্তারিত তথ্য দেখুন',
        'backToList' => 'বাটন: তালিকায় ফিরে যান',
        'emptyDefaultTitle' => 'তথ্য না থাকলে সাধারণ বার্তা',
    ],
    'আবেদনযোগ্যতা যাচাই' => [
        'checkerTitle' => 'শিরোনাম: আবেদনযোগ্যতা যাচাই করুন',
        'checkerSubtitle' => 'শিরোনামের নিচের বিবরণ',
        'groupLabel' => 'গ্রুপ নির্বাচনের লেবেল',
        'groupScience' => 'গ্রুপ: বিজ্ঞান',
        'groupCommerce' => 'গ্রুপ: বাণিজ্য',
        'groupArts' => 'গ্রুপ: মানবিক',
        'sscGpaLabel' => 'SSC জিপিএ লেবেল',
        'hscGpaLabel' => 'HSC জিপিএ লেবেল',
        'gpaPlaceholder' => 'জিপিএ ঘরের নমুনা লেখা',
        'subjectGpaLabel' => 'বিষয়ভিত্তিক জিপিএ শিরোনাম',
        'sscYearLabel' => 'SSC পাসের সাল লেবেল',
        'hscYearLabel' => 'HSC পাসের সাল লেবেল',
        'mobileLabel' => 'মোবাইল নম্বর লেবেল',
        'mobilePlaceholder' => 'মোবাইল নম্বর ঘরের নমুনা লেখা',
        'yearPlaceholder' => 'সালের ঘরের নমুনা ("যেমন: {year}")',
        'checkButton' => 'বাটন: যাচাই করুন',
        'checkerDisclaimer' => 'ফলাফলের নিচের সতর্কবার্তা',
        'noEligibleTitle' => 'কোনো প্রতিষ্ঠান না মিললে শিরোনাম',
        'noEligibleDesc' => 'কোনো প্রতিষ্ঠান না মিললে বিবরণ',
        'eligibleCountPrefix' => 'ফলাফল: "আপনি মোট" (আগের অংশ)',
        'eligibleCountSuffix' => 'ফলাফল: "টি ইউনিটে আবেদনযোগ্য" (পরের অংশ)',
        'minRequirements' => 'ফলাফলে "সর্বনিম্ন যোগ্যতা" লেবেল',
        'noteLabel' => 'ফলাফলে "টীকা" লেবেল',
    ],
    'ত্রুটি ও বার্তা' => [
        'errorTitle' => 'তথ্য লোড না হলে শিরোনাম',
        'errorDesc' => 'তথ্য লোড না হলে বিবরণ',
        'retry' => 'বাটন: আবার চেষ্টা করুন',
        'notFoundTitle' => 'প্রতিষ্ঠান না পাওয়া গেলে বার্তা',
    ],
];
